export { default as HomeLayout } from './HomeLayout'
export { default as Error } from './Error'
export { default as Home } from './Home'
export { default as About } from './About'
export { default as Portfolio } from './Portfolio'
export { default as Contact } from './Contact'
export { default as Studio } from './Studio'